# This is a workflow for deploying to AWS S3

name: Deploy to AWS S3

env:
  AWS_REGION: us-west-2
  out_dir: ./out

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"

      # Installs necessary dependencies for build
      - name: Install Dependencies
        run: npm install

      # Build and export app to static HTML
      - name: Build & Export
        run: npm run build

      # Configure AWS credentials for S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Sync with AWS S3
      - name: AWS S3 Sync
        run: aws s3 sync ${{ env.out_dir }} s3://${{ secrets.AWS_S3_BUCKET }}
